name: Build RPMs

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the Fedora kernel with the ACS override patch in this repo
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2

      - name: Build the RPMs
        id: build-rpms
        uses: ./

      - name: Upload the RPMs as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: kernel-${{ steps.build-rpms.outputs.kernel-version }}-acs-override-rpms
          path: /home/runner/work/_temp/_github_home/rpmbuild/RPMS/x86_64/
